version: "3"

services:
  chall:
    build: .
    container_name: chall
    restart: always
    environment:
      - FLAG=CNSS{flag}
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=admin123
    ports:
      - "53000:3000"